export const SET_WINDOW1_IMAGE = 'SET_WINDOW1_IMAGE';
export const SET_WINDOW2_IMAGE = 'SET_WINDOW2_IMAGE';
export const SET_PAGEURL = 'SET_PAGEURL';
export const REMOVE_PAGEURL = 'REMOVE_PAGEURL';
export const LIKED_STATE = 'LIKED_STATE';
export const SET_IMAGE1_ID = 'SET_IMAGE1_ID';
export const SET_IMAGE2_ID = 'SET_IMAGE2_ID';
